# Generated by Django 5.2.11 on 2026-02-13 09:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=30, verbose_name='회원 아이디')),
                ('member_name', models.CharField(blank=True, max_length=30, verbose_name='회원 이름')),
                ('out_desc', models.TextField(blank=True, verbose_name='탈퇴사유')),
                ('out_dt', models.DateTimeField(blank=True, null=True, verbose_name='탈퇴일')),
            ],
            options={
                'verbose_name': '탈퇴회원',
                'verbose_name_plural': '탈퇴회원',
                'db_table': 'accounts_outmember',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('member_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='회원코드(레거시)')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='이름')),
                ('tel', models.CharField(blank=True, max_length=14, verbose_name='전화번호')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='휴대전화')),
                ('zipcode', models.CharField(blank=True, max_length=7, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='상세주소')),
                ('sms_consent', models.CharField(default='N', max_length=1, verbose_name='SMS 수신동의')),
                ('mail_consent', models.CharField(default='N', max_length=1, verbose_name='메일 수신동의')),
                ('status', models.CharField(default='N', max_length=1, verbose_name='회원상태')),
                ('login_count', models.IntegerField(default=0, verbose_name='로그인횟수')),
                ('failed_count', models.IntegerField(default=0, verbose_name='로그인실패횟수')),
                ('join_ncsafe', models.CharField(blank=True, max_length=255, verbose_name='NICE 인증값')),
                ('birth', models.CharField(blank=True, max_length=12, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, max_length=1, verbose_name='성별')),
                ('join_safe_di', models.CharField(blank=True, max_length=255, verbose_name='NICE DI')),
                ('join_ipin_key', models.CharField(blank=True, max_length=255, verbose_name='아이핀 키')),
                ('join_safegbn', models.CharField(blank=True, max_length=20, verbose_name='인증구분')),
                ('join_path', models.CharField(blank=True, max_length=2, verbose_name='가입경로')),
                ('secession_desc', models.TextField(blank=True, verbose_name='탈퇴사유')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'accounts_member',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MemberChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='자녀코드(레거시)')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='이름')),
                ('child_id', models.CharField(blank=True, max_length=25, verbose_name='자녀 아이디')),
                ('child_pwd', models.CharField(blank=True, max_length=200, verbose_name='자녀 비밀번호')),
                ('birth', models.CharField(blank=True, max_length=12, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, max_length=1, verbose_name='성별')),
                ('school', models.CharField(blank=True, max_length=40, verbose_name='학교')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='학년')),
                ('height', models.CharField(blank=True, max_length=4, verbose_name='키')),
                ('weight', models.CharField(blank=True, max_length=4, verbose_name='몸무게')),
                ('size', models.CharField(blank=True, max_length=4, verbose_name='사이즈')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='휴대전화')),
                ('login_count', models.IntegerField(default=0, verbose_name='로그인횟수')),
                ('status', models.CharField(default='N', max_length=1, verbose_name='상태')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('secession_desc', models.TextField(blank=True, verbose_name='탈퇴사유')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('join_path', models.CharField(blank=True, max_length=2, verbose_name='가입경로')),
                ('card_num', models.CharField(blank=True, max_length=8, verbose_name='카드번호')),
                ('course_state', models.CharField(blank=True, max_length=3, verbose_name='수강상태')),
                ('parent', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학부모')),
            ],
            options={
                'verbose_name': '자녀',
                'verbose_name_plural': '자녀',
                'db_table': 'accounts_memberchild',
            },
        ),
    ]
