# Generated by Django 5.2.11 on 2026-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberchild',
            name='child_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='자녀 아이디'),
        ),
    ]
