# Generated by Django 5.2.11 on 2026-02-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_memberchild_child_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='idx_member_name'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='idx_member_phone'),
        ),
        migrations.AddIndex(
            model_name='memberchild',
            index=models.Index(fields=['course_state'], name='idx_child_course_state'),
        ),
    ]
