# Generated by Django 5.2.11 on 2026-02-14 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_seq', models.IntegerField(unique=True, verbose_name='게시글번호')),
                ('b_ref', models.IntegerField(default=0, verbose_name='답글그룹번호')),
                ('b_level', models.IntegerField(default=0, verbose_name='답글깊이')),
                ('b_step', models.IntegerField(default=0, verbose_name='답글순서')),
                ('b_gbn', models.CharField(max_length=3, verbose_name='게시판구분')),
                ('b_notice_yn', models.CharField(default='N', max_length=1, verbose_name='공지여부')),
                ('b_title', models.CharField(max_length=200, verbose_name='제목')),
                ('b_content', models.TextField(blank=True, verbose_name='내용')),
                ('b_hit', models.IntegerField(default=0, verbose_name='조회수')),
                ('b_commend', models.IntegerField(default=0, verbose_name='추천수')),
                ('insert_name', models.CharField(blank=True, max_length=20, verbose_name='작성자명')),
                ('insert_id', models.CharField(blank=True, max_length=12, verbose_name='작성자ID')),
                ('insert_type', models.CharField(blank=True, max_length=1, verbose_name='작성자타입')),
                ('insert_dt', models.CharField(blank=True, max_length=20, verbose_name='작성일')),
                ('insert_ip', models.CharField(blank=True, max_length=15, verbose_name='IP주소')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'board_board',
                'ordering': ['-b_seq'],
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_gbn', models.CharField(blank=True, max_length=3, verbose_name='게시판구분')),
                ('comment', models.TextField(verbose_name='댓글내용')),
                ('insert_name', models.CharField(blank=True, max_length=20, verbose_name='작성자명')),
                ('insert_id', models.CharField(blank=True, max_length=20, verbose_name='작성자ID')),
                ('insert_type', models.CharField(blank=True, max_length=1, verbose_name='작성자타입')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='작성일')),
                ('insert_ip', models.CharField(blank=True, max_length=15, verbose_name='IP주소')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.board', to_field='b_seq', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'board_boardcomment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_img', models.CharField(blank=True, max_length=300, verbose_name='이미지파일')),
                ('bs_thumimg', models.CharField(blank=True, max_length=300, verbose_name='썸네일')),
                ('bs_file', models.CharField(blank=True, max_length=300, verbose_name='첨부파일')),
                ('bs_downcnt', models.IntegerField(default=0, verbose_name='다운로드수')),
                ('bs_no', models.IntegerField(default=0, verbose_name='순번')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=12, verbose_name='등록자ID')),
                ('daum_uploadhost', models.CharField(blank=True, max_length=255, verbose_name='Daum호스트')),
                ('daum_vid', models.CharField(blank=True, max_length=128, verbose_name='Daum VID')),
                ('daum_thimg', models.CharField(blank=True, max_length=255, verbose_name='Daum썸네일')),
                ('daum_width', models.CharField(blank=True, max_length=4, verbose_name='Daum너비')),
                ('daum_height', models.CharField(blank=True, max_length=4, verbose_name='Daum높이')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.board', to_field='b_seq', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
                'db_table': 'board_boardfile',
                'ordering': ['bs_no'],
            },
        ),
    ]
