# Generated by Django 5.2.11 on 2026-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_title', models.CharField(max_length=200, verbose_name='팝업제목')),
                ('pop_begin_date', models.CharField(blank=True, max_length=10, verbose_name='게시시작일')),
                ('pop_end_date', models.CharField(blank=True, max_length=10, verbose_name='게시종료일')),
                ('pop_img', models.CharField(blank=True, max_length=200, verbose_name='팝업이미지')),
                ('pop_url', models.CharField(blank=True, max_length=500, verbose_name='링크URL')),
                ('pop_width', models.CharField(blank=True, max_length=10, verbose_name='너비')),
                ('pop_height', models.CharField(blank=True, max_length=10, verbose_name='높이')),
                ('pop_left', models.CharField(blank=True, max_length=10, verbose_name='좌측위치')),
                ('pop_top', models.CharField(blank=True, max_length=10, verbose_name='상단위치')),
                ('pop_urltype', models.CharField(default='I', max_length=1, verbose_name='링크타입')),
                ('pop_gbn', models.CharField(default='P', max_length=1, verbose_name='팝업형식')),
                ('pop_yn', models.CharField(default='Y', max_length=1, verbose_name='활성여부')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=20, verbose_name='등록자ID')),
            ],
            options={
                'verbose_name': '팝업',
                'verbose_name_plural': '팝업',
                'db_table': 'board_popup',
                'ordering': ['-id'],
            },
        ),
    ]
