# Generated by Django 5.2.11 on 2026-02-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_seq', models.CharField(max_length=4, unique=True, verbose_name='포인트코드')),
                ('point_title', models.CharField(max_length=30, verbose_name='포인트명')),
                ('use_yn', models.CharField(default='Y', max_length=2, verbose_name='사용여부')),
                ('app_gbn', models.CharField(choices=[('S', '적립'), ('U', '사용')], max_length=2, verbose_name='적립/사용구분')),
                ('save_gbn', models.CharField(blank=True, choices=[('PE', '비율(%)'), ('PO', '정액(포인트)')], max_length=2, verbose_name='적립방식')),
                ('save_point', models.IntegerField(default=0, verbose_name='적립포인트/비율')),
                ('limit_point', models.IntegerField(default=0, verbose_name='기준금액/최소사용금액')),
            ],
            options={
                'verbose_name': '포인트 설정',
                'verbose_name_plural': '포인트 설정',
                'db_table': 'points_pointconfig',
                'ordering': ['point_seq'],
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_dt', models.CharField(blank=True, max_length=12, verbose_name='포인트일자')),
                ('member_name', models.CharField(blank=True, max_length=20, verbose_name='회원명')),
                ('app_gbn', models.CharField(choices=[('S', '적립'), ('U', '사용')], max_length=2, verbose_name='적립/사용')),
                ('app_point', models.IntegerField(default=0, verbose_name='포인트')),
                ('point_desc', models.CharField(blank=True, max_length=200, verbose_name='내용')),
                ('order_no', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('confirm_id', models.CharField(blank=True, max_length=100, verbose_name='확인자ID')),
                ('desc_detail', models.CharField(blank=True, max_length=1000, verbose_name='상세내용')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=20, verbose_name='등록자')),
                ('member', models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_histories', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='회원')),
            ],
            options={
                'verbose_name': '포인트 내역',
                'verbose_name_plural': '포인트 내역',
                'db_table': 'points_pointhistory',
                'ordering': ['-insert_dt', '-id'],
            },
        ),
    ]
