# Generated by Django 5.2.11 on 2026-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhistory',
            name='member_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='회원명'),
        ),
    ]
