# Generated by Django 5.2.11 on 2026-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.CharField(max_length=12, verbose_name='관리자ID')),
                ('login_dt', models.DateTimeField(auto_now_add=True, verbose_name='로그인일시')),
                ('login_ip', models.CharField(blank=True, max_length=45, verbose_name='접속IP')),
            ],
            options={
                'verbose_name': '관리자 로그인 이력',
                'verbose_name_plural': '관리자 로그인 이력',
                'db_table': 'office_loginhistory',
                'ordering': ['-login_dt'],
            },
        ),
        migrations.CreateModel(
            name='OfficeUser',
            fields=[
                ('office_code', models.AutoField(primary_key=True, serialize=False, verbose_name='관리자코드')),
                ('office_name', models.CharField(max_length=20, verbose_name='표시명')),
                ('office_realname', models.CharField(blank=True, max_length=20, verbose_name='실명')),
                ('office_id', models.CharField(max_length=12, unique=True, verbose_name='아이디')),
                ('office_pwd', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('office_part', models.CharField(blank=True, max_length=50, verbose_name='부서명')),
                ('office_mail', models.CharField(blank=True, max_length=100, verbose_name='이메일')),
                ('office_hp', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('power_level', models.CharField(blank=True, max_length=20, verbose_name='메뉴권한')),
                ('use_auth', models.CharField(choices=[('W', '주니어'), ('E', '이마트')], default='W', max_length=1, verbose_name='접속구분')),
                ('coach_code', models.CharField(blank=True, max_length=10, verbose_name='코치코드')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자',
                'db_table': 'office_officeuser',
                'ordering': ['office_name'],
            },
        ),
    ]
