# Generated by Django 5.2.11 on 2026-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeuser',
            name='coach_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='코치코드'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='office_mail',
            field=models.CharField(blank=True, max_length=128, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='office_name',
            field=models.CharField(max_length=30, verbose_name='표시명'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='office_part',
            field=models.CharField(blank=True, max_length=20, verbose_name='부서명'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='office_realname',
            field=models.CharField(blank=True, max_length=30, verbose_name='실명'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='power_level',
            field=models.CharField(blank=True, max_length=40, verbose_name='메뉴권한'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='use_auth',
            field=models.CharField(choices=[('W', '주니어'), ('E', '이마트')], default='W', max_length=2, verbose_name='접속구분'),
        ),
    ]
