# Generated by Django 5.2.11 on 2026-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_officeuser_coach_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeloginhistory',
            name='action',
            field=models.CharField(default='로그인', max_length=20, verbose_name='활동'),
        ),
        migrations.AddField(
            model_name='officeloginhistory',
            name='memo',
            field=models.CharField(blank=True, max_length=100, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='officeloginhistory',
            name='login_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='일시'),
        ),
    ]
