# Generated by Django 5.2.11 on 2026-02-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_code', models.IntegerField(unique=True, verbose_name='코치코드')),
                ('coach_name', models.CharField(max_length=60, verbose_name='코치명')),
                ('coach_level', models.CharField(blank=True, max_length=10, verbose_name='직급')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='연락처')),
                ('dpart', models.CharField(blank=True, max_length=40, verbose_name='부서')),
                ('coach_s_img', models.CharField(blank=True, max_length=200, verbose_name='이미지')),
                ('use_gbn', models.CharField(default='Y', max_length=1, verbose_name='사용여부')),
                ('order_seq', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '코치',
                'verbose_name_plural': '코치',
                'db_table': 'courses_coach',
                'ordering': ['order_seq', 'coach_name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True, verbose_name='프로모션ID')),
                ('kind', models.CharField(blank=True, max_length=20, verbose_name='종류')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='요약')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('discount', models.IntegerField(default=0, verbose_name='할인액')),
                ('discount_unit', models.CharField(blank=True, max_length=1, verbose_name='할인단위')),
                ('is_price_limit', models.CharField(blank=True, max_length=1, verbose_name='금액제한여부')),
                ('min_price', models.IntegerField(default=0, verbose_name='최소금액')),
                ('max_price', models.IntegerField(default=0, verbose_name='최대금액')),
                ('issue_mode', models.IntegerField(default=0, verbose_name='발급모드')),
                ('use_mode', models.IntegerField(default=0, verbose_name='사용모드')),
                ('is_use', models.CharField(default='T', max_length=1, verbose_name='사용여부')),
                ('local_code', models.IntegerField(blank=True, null=True, verbose_name='권역코드')),
                ('sta_code', models.IntegerField(blank=True, null=True, verbose_name='구장코드')),
                ('member_code', models.CharField(blank=True, max_length=30, verbose_name='회원코드')),
                ('reg_date', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '프로모션',
                'verbose_name_plural': '프로모션',
                'db_table': 'courses_promotion',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_code', models.IntegerField(unique=True, verbose_name='구장코드')),
                ('local_code', models.IntegerField(default=0, verbose_name='권역코드')),
                ('sta_name', models.CharField(max_length=100, verbose_name='구장명')),
                ('sta_nickname', models.CharField(blank=True, max_length=100, verbose_name='구장별칭')),
                ('sta_phone', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
                ('sta_address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('sta_s_img', models.CharField(blank=True, max_length=200, verbose_name='소이미지')),
                ('sta_l_img', models.CharField(blank=True, max_length=200, verbose_name='대이미지')),
                ('sta_p_img', models.CharField(blank=True, max_length=200, verbose_name='페이지이미지')),
                ('sta_m_img', models.CharField(blank=True, max_length=200, verbose_name='모바일이미지')),
                ('sta_desc', models.TextField(blank=True, verbose_name='소개')),
                ('sta_coach', models.CharField(blank=True, max_length=100, verbose_name='담당코치')),
                ('use_gbn', models.CharField(default='Y', max_length=1, verbose_name='사용여부')),
                ('kapa_tot', models.IntegerField(default=0, verbose_name='총정원')),
                ('inve', models.CharField(blank=True, max_length=10, verbose_name='투자구분')),
                ('grou', models.CharField(blank=True, max_length=10, verbose_name='그룹구분')),
                ('three_lecyn', models.CharField(blank=True, max_length=1, verbose_name='3회체험여부')),
                ('order_seq', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('location_url', models.TextField(blank=True, verbose_name='지도URL')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '구장',
                'verbose_name_plural': '구장',
                'db_table': 'courses_stadium',
                'ordering': ['order_seq', 'sta_name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.IntegerField(unique=True, verbose_name='강좌코드')),
                ('local_code', models.IntegerField(default=0, verbose_name='권역코드')),
                ('lecture_title', models.CharField(blank=True, max_length=100, verbose_name='강좌명')),
                ('lec_age', models.CharField(blank=True, max_length=40, verbose_name='대상')),
                ('lecture_day', models.IntegerField(default=0, verbose_name='요일')),
                ('lecture_time', models.CharField(blank=True, max_length=10, verbose_name='시간')),
                ('class_gbn', models.CharField(blank=True, max_length=5, verbose_name='클래스구분')),
                ('class_gbn2', models.CharField(blank=True, max_length=5, verbose_name='반구분')),
                ('lec_price', models.IntegerField(default=0, verbose_name='수강료')),
                ('stu_cnt', models.IntegerField(default=0, verbose_name='정원')),
                ('sub_coach', models.CharField(blank=True, max_length=60, verbose_name='보조코치')),
                ('dc_2', models.IntegerField(default=0, verbose_name='주2회할인')),
                ('dc_3', models.IntegerField(default=0, verbose_name='주3회할인')),
                ('dc_4', models.IntegerField(default=0, verbose_name='주4회할인')),
                ('use_gbn', models.CharField(default='Y', max_length=1, verbose_name='사용여부')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures_as_coach', to='courses.coach', verbose_name='담당코치')),
                ('t_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures_as_tcoach', to='courses.coach', verbose_name='수업코치')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.stadium', verbose_name='구장')),
            ],
            options={
                'verbose_name': '강좌',
                'verbose_name_plural': '강좌',
                'db_table': 'courses_lecture',
            },
        ),
        migrations.CreateModel(
            name='StadiumGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_year', models.IntegerField(verbose_name='연도')),
                ('sta_month', models.CharField(max_length=2, verbose_name='월')),
                ('sta_goal', models.IntegerField(default=0, verbose_name='목표인원')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='courses.stadium', verbose_name='구장')),
            ],
            options={
                'verbose_name': '구장목표',
                'verbose_name_plural': '구장목표',
                'db_table': 'courses_stadiumgoal',
            },
        ),
        migrations.CreateModel(
            name='StadiumCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.CASCADE, related_name='coach_stadiums', to='courses.coach', verbose_name='코치')),
                ('stadium', models.ForeignKey(db_column='stadium_id', on_delete=django.db.models.deletion.CASCADE, related_name='stadium_coaches', to='courses.stadium', verbose_name='구장')),
            ],
            options={
                'verbose_name': '구장-코치',
                'verbose_name_plural': '구장-코치',
                'db_table': 'courses_stadiumcoach',
                'unique_together': {('stadium', 'coach')},
            },
        ),
    ]
