# Generated by Django 5.2.11 on 2026-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_unit',
            field=models.CharField(blank=True, max_length=5, verbose_name='할인단위'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_price_limit',
            field=models.CharField(blank=True, max_length=5, verbose_name='금액제한여부'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_use',
            field=models.CharField(default='T', max_length=5, verbose_name='사용여부'),
        ),
    ]
