# Generated by Django 5.2.11 on 2026-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_promotion_discount_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_uid', models.IntegerField(verbose_name='프로모션ID')),
                ('member_id', models.CharField(max_length=30, verbose_name='회원아이디')),
                ('child_id', models.CharField(max_length=25, verbose_name='자녀아이디')),
                ('used', models.CharField(default='T', max_length=1, verbose_name='사용여부')),
                ('is_trash', models.CharField(default='T', max_length=1, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name': '프로모션회원',
                'verbose_name_plural': '프로모션회원',
                'db_table': 'courses_promotionmember',
            },
        ),
        migrations.CreateModel(
            name='LectureSelDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.IntegerField(verbose_name='강좌코드')),
                ('syear', models.IntegerField(verbose_name='연도')),
                ('smonth', models.IntegerField(verbose_name='월')),
                ('sday', models.IntegerField(verbose_name='일')),
                ('admin_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '수업일정',
                'verbose_name_plural': '수업일정',
                'db_table': 'courses_lectureselday',
                'unique_together': {('lecture_code', 'syear', 'smonth', 'sday')},
            },
        ),
    ]
