# Generated by Django 5.2.11 on 2026-02-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_promotionmember_lectureselday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_code', models.IntegerField(default=0, verbose_name='구장코드')),
                ('local_code', models.IntegerField(default=0, verbose_name='권역코드')),
                ('training_dt', models.DateField(blank=True, null=True, verbose_name='훈련일자')),
                ('training_desc', models.TextField(blank=True, verbose_name='훈련내용')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '훈련일정',
                'verbose_name_plural': '훈련일정',
                'db_table': 'courses_lecturetraining',
                'ordering': ['training_dt'],
            },
        ),
    ]
