# Generated by Django 5.2.11 on 2026-02-14 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=16, verbose_name='회원ID')),
                ('member_name', models.CharField(blank=True, max_length=20, verbose_name='회원명')),
                ('child_id', models.CharField(blank=True, max_length=16, verbose_name='자녀ID')),
                ('child_name', models.CharField(blank=True, max_length=20, verbose_name='자녀명')),
                ('consult_name', models.CharField(max_length=20, verbose_name='신청자명')),
                ('consult_tel', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('consult_gbn', models.CharField(blank=True, max_length=10, verbose_name='구분')),
                ('consult_title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('consult_content', models.TextField(blank=True, verbose_name='내용')),
                ('consult_pwd', models.CharField(blank=True, max_length=4, verbose_name='비밀번호')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('consult_dt', models.DateTimeField(blank=True, null=True, verbose_name='상담일시')),
                ('manage_id', models.CharField(blank=True, max_length=16, verbose_name='관리자ID')),
                ('local_code', models.CharField(blank=True, max_length=20, verbose_name='권역코드')),
                ('sta_code', models.CharField(blank=True, max_length=20, verbose_name='구장코드')),
                ('stu_name', models.CharField(blank=True, max_length=30, verbose_name='수강생명')),
                ('stu_sex', models.CharField(blank=True, max_length=1, verbose_name='성별')),
                ('stu_age', models.IntegerField(default=0, verbose_name='나이')),
                ('path_code', models.IntegerField(default=44, verbose_name='신청경로코드')),
                ('line_code', models.IntegerField(default=33, verbose_name='접수경로코드')),
                ('company_name', models.CharField(blank=True, max_length=30, verbose_name='회사명')),
                ('com_employee_no', models.CharField(blank=True, max_length=10, verbose_name='직원번호')),
            ],
            options={
                'verbose_name': '상담',
                'verbose_name_plural': '상담',
                'db_table': 'consult_consult',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=20, verbose_name='신청자명')),
                ('jphone1', models.CharField(blank=True, max_length=5, verbose_name='전화1')),
                ('jphone2', models.CharField(blank=True, max_length=5, verbose_name='전화2')),
                ('jphone3', models.CharField(blank=True, max_length=5, verbose_name='전화3')),
                ('jlocal', models.CharField(blank=True, max_length=30, verbose_name='지역')),
                ('j_date', models.DateTimeField(blank=True, null=True, verbose_name='신청일')),
                ('confirm_memo', models.TextField(blank=True, verbose_name='확인메모')),
                ('confirm_yn', models.CharField(default='N', max_length=1, verbose_name='확인여부')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('confirm_id', models.CharField(blank=True, max_length=20, verbose_name='확인자ID')),
                ('confirm_name', models.CharField(blank=True, max_length=20, verbose_name='확인자명')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='확인일')),
                ('consult_gbn', models.CharField(blank=True, max_length=10, verbose_name='구분')),
            ],
            options={
                'verbose_name': '무료체험신청',
                'verbose_name_plural': '무료체험신청',
                'db_table': 'consult_consultfree',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_gbn', models.CharField(default='L', max_length=1, verbose_name='등록구분')),
                ('reg_name', models.CharField(max_length=100, verbose_name='지역명')),
                ('mphone', models.CharField(blank=True, max_length=20, verbose_name='담당자전화')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name': '상담지역',
                'verbose_name_plural': '상담지역',
                'db_table': 'consult_consultregion',
                'ordering': ['reg_name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_category', models.IntegerField(blank=True, null=True, verbose_name='상담분류코드')),
                ('consult_answer', models.TextField(blank=True, verbose_name='답변')),
                ('con_answer_dt', models.DateTimeField(blank=True, null=True, verbose_name='답변일시')),
                ('coach_code', models.IntegerField(blank=True, null=True, verbose_name='담당코치코드')),
                ('stat_code', models.IntegerField(default=76, verbose_name='상담상태')),
                ('receive_code', models.IntegerField(blank=True, null=True, verbose_name='접수코드')),
                ('cus_stat_code', models.IntegerField(blank=True, null=True, verbose_name='고객상태코드')),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='consult.consult', verbose_name='상담')),
            ],
            options={
                'verbose_name': '상담답변',
                'verbose_name_plural': '상담답변',
                'db_table': 'consult_consultanswer',
            },
        ),
    ]
