# Generated by Django 5.2.11 on 2026-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_tx', models.CharField(blank=True, max_length=10, verbose_name='요청타입')),
                ('use_pay_method', models.CharField(blank=True, max_length=20, verbose_name='결제수단코드')),
                ('res_cd', models.CharField(blank=True, max_length=10, verbose_name='응답코드')),
                ('res_msg', models.CharField(blank=True, max_length=200, verbose_name='응답메시지')),
                ('amount', models.IntegerField(default=0, verbose_name='결제금액')),
                ('ordr_idxx', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('good_name', models.CharField(blank=True, max_length=200, verbose_name='상품명')),
                ('buyr_name', models.CharField(blank=True, max_length=60, verbose_name='구매자명')),
                ('member_num', models.CharField(blank=True, max_length=30, verbose_name='회원아이디')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '결제실패',
                'verbose_name_plural': '결제실패',
                'db_table': 'payments_paymentfail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentKCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_tx', models.CharField(blank=True, max_length=10, verbose_name='요청타입')),
                ('use_pay_method', models.CharField(blank=True, max_length=20, verbose_name='결제수단코드')),
                ('bsucc', models.CharField(blank=True, max_length=5, verbose_name='성공여부')),
                ('res_cd', models.CharField(blank=True, max_length=10, verbose_name='응답코드')),
                ('res_msg', models.CharField(blank=True, max_length=200, verbose_name='응답메시지')),
                ('res_msg_bsucc', models.CharField(blank=True, max_length=200, verbose_name='성공메시지')),
                ('amount', models.IntegerField(default=0, verbose_name='결제금액')),
                ('ordr_idxx', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('tno', models.CharField(blank=True, max_length=100, verbose_name='거래번호')),
                ('good_mny', models.IntegerField(default=0, verbose_name='상품금액')),
                ('good_name', models.CharField(blank=True, max_length=200, verbose_name='상품명')),
                ('buyr_name', models.CharField(blank=True, max_length=60, verbose_name='구매자명')),
                ('buyr_tel1', models.CharField(blank=True, max_length=20, verbose_name='구매자전화1')),
                ('buyr_tel2', models.CharField(blank=True, max_length=20, verbose_name='구매자전화2')),
                ('buyr_mail', models.CharField(blank=True, max_length=100, verbose_name='구매자메일')),
                ('app_time', models.CharField(blank=True, max_length=20, verbose_name='승인시간')),
                ('card_cd', models.CharField(blank=True, max_length=10, verbose_name='카드코드')),
                ('card_name', models.CharField(blank=True, max_length=50, verbose_name='카드명')),
                ('app_no', models.CharField(blank=True, max_length=20, verbose_name='승인번호')),
                ('noinf', models.CharField(blank=True, max_length=5, verbose_name='무이자여부')),
                ('quota', models.CharField(blank=True, max_length=3, verbose_name='할부개월')),
                ('bank_name', models.CharField(blank=True, max_length=20, verbose_name='은행명')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='은행코드')),
                ('depositor', models.CharField(blank=True, max_length=20, verbose_name='예금주')),
                ('account', models.CharField(blank=True, max_length=30, verbose_name='계좌번호')),
                ('va_date', models.CharField(blank=True, max_length=20, verbose_name='가상계좌입금기한')),
                ('pay_seq', models.IntegerField(default=0, verbose_name='입단번호')),
                ('member_num', models.CharField(blank=True, max_length=30, verbose_name='회원아이디')),
                ('pg_gbn', models.CharField(blank=True, max_length=5, verbose_name='PG구분')),
                ('add_pnt', models.IntegerField(default=0, verbose_name='추가포인트')),
                ('use_pnt', models.IntegerField(default=0, verbose_name='사용포인트')),
                ('rsv_pnt', models.IntegerField(default=0, verbose_name='적립포인트')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': 'KCP결제',
                'verbose_name_plural': 'KCP결제',
                'db_table': 'payments_paymentkcp',
                'ordering': ['-id'],
            },
        ),
    ]
