# Generated by Django 5.2.11 on 2026-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttoss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoss',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='주문번호'),
        ),
    ]
