# Generated by Django 5.2.11 on 2026-02-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGroup',
            fields=[
                ('grpcode', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='그룹코드')),
                ('grpcode_name', models.CharField(blank=True, max_length=20, verbose_name='그룹명')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=12, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '코드그룹',
                'verbose_name_plural': '코드그룹',
                'db_table': 'common_codegroup',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_price', models.IntegerField(default=0, verbose_name='입단비')),
                ('pk_price', models.IntegerField(default=0, verbose_name='PK비')),
                ('insert_id', models.CharField(blank=True, max_length=50, verbose_name='등록자')),
                ('insert_dt', models.DateTimeField(verbose_name='등록일')),
            ],
            options={
                'verbose_name': '시스템설정',
                'verbose_name_plural': '시스템설정',
                'db_table': 'common_setting',
            },
        ),
        migrations.CreateModel(
            name='CodeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.IntegerField(verbose_name='서브코드')),
                ('code_name', models.CharField(blank=True, max_length=40, verbose_name='코드명')),
                ('code_desc', models.CharField(blank=True, max_length=200, verbose_name='코드설명')),
                ('code_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=12, verbose_name='등록자')),
                ('yard_seq', models.CharField(blank=True, max_length=2, verbose_name='구장순서')),
                ('group', models.ForeignKey(db_column='grpcode', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='common.codegroup', verbose_name='그룹코드')),
            ],
            options={
                'verbose_name': '코드값',
                'verbose_name_plural': '코드값',
                'db_table': 'common_codevalue',
            },
        ),
    ]
