# Generated by Django 5.2.11 on 2026-02-13 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_memberchild_child_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_code', models.IntegerField(default=0, verbose_name='권역코드')),
                ('sta_code', models.IntegerField(default=0, verbose_name='구장코드')),
                ('lecture_code', models.IntegerField(default=0, verbose_name='강좌코드')),
                ('member_id', models.CharField(max_length=30, verbose_name='학부모 아이디')),
                ('member_name', models.CharField(blank=True, max_length=60, verbose_name='학부모 이름')),
                ('child_id', models.CharField(max_length=25, verbose_name='자녀 아이디')),
                ('child_name', models.CharField(blank=True, max_length=20, verbose_name='자녀 이름')),
                ('wait_seq', models.IntegerField(default=0, verbose_name='대기순번')),
                ('trans_gbn', models.CharField(default='N', max_length=1, verbose_name='전환여부')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '대기자',
                'verbose_name_plural': '대기자',
                'db_table': 'enrollment_waitstudent',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_stats', models.CharField(choices=[('PY', '결제완료'), ('UN', '미결제')], default='UN', max_length=2, verbose_name='결제상태')),
                ('pay_method', models.CharField(blank=True, choices=[('CARD', '카드'), ('R', '계좌이체'), ('VACCT', '가상계좌')], max_length=5, verbose_name='결제방법')),
                ('pay_price', models.IntegerField(default=0, verbose_name='결제금액')),
                ('pay_dt', models.DateTimeField(blank=True, null=True, verbose_name='결제일시')),
                ('lecture_stats', models.CharField(choices=[('LY', '수강확정'), ('LP', '일시정지'), ('LN', '취소'), ('PN', '대기')], default='LN', max_length=2, verbose_name='수강상태')),
                ('lec_cycle', models.IntegerField(default=1, verbose_name='주간횟수')),
                ('lec_period', models.IntegerField(default=3, verbose_name='수강기간(월)')),
                ('start_dt', models.CharField(blank=True, max_length=6, verbose_name='시작년월')),
                ('end_dt', models.CharField(blank=True, max_length=6, verbose_name='종료년월')),
                ('apply_gubun', models.CharField(choices=[('NEW', '신규'), ('RE', '재등록'), ('RENEW', '갱신')], default='NEW', max_length=5, verbose_name='신청구분')),
                ('source_gubun', models.CharField(default='01', max_length=2, verbose_name='신청출처')),
                ('recommend_id', models.CharField(blank=True, max_length=30, verbose_name='추천인ID')),
                ('discount1_id', models.CharField(blank=True, max_length=30, verbose_name='할인1 ID')),
                ('discount1_price', models.IntegerField(default=0, verbose_name='할인1 금액')),
                ('discount2_id', models.CharField(blank=True, max_length=30, verbose_name='할인2 ID')),
                ('discount2_price', models.IntegerField(default=0, verbose_name='할인2 금액')),
                ('discount3_id', models.CharField(blank=True, max_length=30, verbose_name='할인3 ID')),
                ('discount3_price', models.IntegerField(default=0, verbose_name='할인3 금액')),
                ('discount4_id', models.CharField(blank=True, max_length=30, verbose_name='할인4 ID')),
                ('discount4_price', models.IntegerField(default=0, verbose_name='할인4 금액')),
                ('discount5_id', models.CharField(blank=True, max_length=30, verbose_name='할인5 ID')),
                ('discount5_price', models.IntegerField(default=0, verbose_name='할인5 금액')),
                ('discount6_id', models.CharField(blank=True, max_length=30, verbose_name='할인6 ID')),
                ('discount6_price', models.IntegerField(default=0, verbose_name='할인6 금액')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('child', models.ForeignKey(db_column='child_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.memberchild', to_field='child_id', verbose_name='자녀')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학부모')),
            ],
            options={
                'verbose_name': '입단신청',
                'verbose_name_plural': '입단신청',
                'db_table': 'enrollment_enrollment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(max_length=4, verbose_name='청구코드')),
                ('bill_desc', models.CharField(blank=True, max_length=100, verbose_name='청구설명')),
                ('bill_amt', models.IntegerField(default=0, verbose_name='청구금액')),
                ('pay_stats', models.CharField(default='UN', max_length=2, verbose_name='결제상태')),
                ('insert_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('enrollment', models.ForeignKey(db_column='no_seq', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='enrollment.enrollment', verbose_name='입단')),
            ],
            options={
                'verbose_name': '청구내역',
                'verbose_name_plural': '청구내역',
                'db_table': 'enrollment_enrollmentbill',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(max_length=4, verbose_name='청구코드')),
                ('course_ym', models.DateField(verbose_name='수강년월')),
                ('course_ym_amt', models.IntegerField(default=0, verbose_name='수강금액')),
                ('lecture_code', models.IntegerField(default=0, verbose_name='강좌코드')),
                ('start_ymd', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('course_stats', models.CharField(default='LY', max_length=2, verbose_name='수강상태')),
                ('enrollment', models.ForeignKey(db_column='no_seq', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='enrollment.enrollment', verbose_name='입단')),
            ],
            options={
                'verbose_name': '수강과정',
                'verbose_name_plural': '수강과정',
                'db_table': 'enrollment_enrollmentcourse',
            },
        ),
    ]
