# Generated by Django 5.2.11 on 2026-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='apply_gubun',
            field=models.CharField(choices=[('NEW', '신규'), ('RE', '재등록'), ('RENEW', '갱신'), ('AGAIN', '재입단')], default='NEW', max_length=5, verbose_name='신청구분'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('CARD', '카드'), ('R', '계좌이체'), ('VACCT', '가상계좌'), ('ACCT', '계좌'), ('BENEFIT', '복지'), ('ZEROPAY', '제로페이'), ('MUCU', '문화상품권'), ('LOTTE', '롯데'), ('ESNC', 'ESNC'), ('GRPY', '그룹페이'), ('EMART', '이마트'), ('SPBA', 'SPBA')], max_length=10, verbose_name='결제방법'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='pay_stats',
            field=models.CharField(choices=[('PY', '결제완료'), ('UN', '미결제'), ('PP', '부분결제'), ('PN', '결제대기'), ('PQ', '환불'), ('PZ', '취소')], default='UN', max_length=2, verbose_name='결제상태'),
        ),
    ]
