# Generated by Django 5.2.11 on 2026-02-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_apply_gubun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=30, verbose_name='학부모ID')),
                ('child_id', models.CharField(blank=True, max_length=30, verbose_name='자녀ID')),
                ('chg_gbn', models.CharField(blank=True, max_length=10, verbose_name='변경구분')),
                ('chg_desc', models.CharField(blank=True, max_length=100, verbose_name='변경설명')),
                ('no_seq', models.IntegerField(default=0, verbose_name='입단번호')),
                ('src_seq', models.IntegerField(default=0, verbose_name='원본번호')),
                ('reg_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('reg_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '변경이력',
                'verbose_name_plural': '변경이력',
                'db_table': 'enrollment_changehistory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_code', models.IntegerField(default=0, verbose_name='권역코드')),
                ('sta_code', models.IntegerField(default=0, verbose_name='구장코드')),
                ('lecture_code', models.IntegerField(default=0, verbose_name='강좌코드')),
                ('child_id', models.CharField(blank=True, max_length=30, verbose_name='자녀ID')),
                ('attendance_dt', models.CharField(blank=True, max_length=10, verbose_name='출석일')),
                ('attendance_gbn', models.CharField(blank=True, choices=[('Y', '출석'), ('N', '결석'), ('A', '보강'), ('R', '우천취소'), ('D', '수업연기'), ('E', '출결제외')], max_length=1, verbose_name='출석구분')),
                ('attendance_desc', models.CharField(blank=True, max_length=100, verbose_name='비고')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('insert_id', models.CharField(blank=True, max_length=16, verbose_name='등록자')),
                ('mata', models.CharField(blank=True, max_length=1, verbose_name='사후처리')),
                ('app_month', models.CharField(blank=True, max_length=7, verbose_name='적용월')),
                ('complete_yn', models.CharField(default='N', max_length=1, verbose_name='완료여부')),
                ('uid', models.IntegerField(default=0, verbose_name='UID')),
                ('match_ymd', models.CharField(blank=True, max_length=8, verbose_name='매칭일')),
                ('ticket_no', models.CharField(blank=True, max_length=20, verbose_name='티켓번호1')),
                ('ticket_no2', models.CharField(blank=True, max_length=20, verbose_name='티켓번호2')),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석',
                'db_table': 'enrollment_attendance',
                'indexes': [models.Index(fields=['attendance_dt'], name='idx_attend_dt'), models.Index(fields=['child_id'], name='idx_attend_child'), models.Index(fields=['lecture_code', 'attendance_dt'], name='idx_attend_lec_dt'), models.Index(fields=['sta_code'], name='idx_attend_sta')],
            },
        ),
    ]
