# Generated by Django 5.2.11 on 2026-02-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_changehistory_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='bigo_content',
            field=models.CharField(blank=True, max_length=500, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cancel_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='취소사유코드'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='취소일'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cancel_desc',
            field=models.CharField(blank=True, max_length=200, verbose_name='취소사유'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='shuttle_yn',
            field=models.CharField(blank=True, max_length=1, verbose_name='셔틀이용'),
        ),
    ]
