# Generated by Django 5.2.11 on 2026-02-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_enrollment_account_no_enrollment_bigo_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitstudent',
            name='bigo',
            field=models.CharField(blank=True, max_length=500, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='waitstudent',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='전화번호'),
        ),
    ]
