# Generated by Django 5.2.11 on 2026-02-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_add_bigo_phone_to_waitstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentCourseSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_seq', models.IntegerField(db_index=True, default=0, verbose_name='원본번호')),
                ('pknum', models.IntegerField(default=0, verbose_name='과정PK')),
                ('no_seq', models.IntegerField(default=0, verbose_name='입단번호')),
                ('bill_code', models.CharField(max_length=4, verbose_name='청구코드')),
                ('course_ym', models.DateField(verbose_name='수강년월')),
                ('course_ym_amt', models.IntegerField(default=0, verbose_name='수강금액')),
                ('lecture_code', models.IntegerField(default=0, verbose_name='강좌코드')),
                ('start_ymd', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('course_stats', models.CharField(default='LY', max_length=2, verbose_name='수강상태')),
                ('ch_name', models.CharField(blank=True, max_length=40, verbose_name='코치명')),
            ],
            options={
                'verbose_name': '수강과정 변경원본',
                'verbose_name_plural': '수강과정 변경원본',
                'db_table': 'enrollment_enrollmentcoursesrc',
            },
        ),
    ]
