# Generated by Django 5.2.11 on 2026-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_enrollmentcoursesrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentcourse',
            name='pknum',
            field=models.IntegerField(db_index=True, default=0, verbose_name='원본PK'),
        ),
    ]
