# Generated by Django 5.2.11 on 2026-02-18 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_idx_member_name_member_idx_member_phone_and_more'),
        ('enrollment', '0007_enrollmentcourse_pknum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['del_chk', 'lecture_stats'], name='idx_enroll_delchk_stats'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['lecture_stats', 'pay_stats'], name='idx_enroll_lec_pay_stats'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['member_id'], name='idx_enroll_member'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['child_id'], name='idx_enroll_child'),
        ),
        migrations.AddIndex(
            model_name='enrollmentbill',
            index=models.Index(fields=['bill_code'], name='idx_bill_code'),
        ),
        migrations.AddIndex(
            model_name='enrollmentbill',
            index=models.Index(fields=['pay_stats'], name='idx_bill_pay_stats'),
        ),
        migrations.AddIndex(
            model_name='enrollmentcourse',
            index=models.Index(fields=['bill_code'], name='idx_ec_bill_code'),
        ),
        migrations.AddIndex(
            model_name='enrollmentcourse',
            index=models.Index(fields=['course_ym'], name='idx_ec_course_ym'),
        ),
        migrations.AddIndex(
            model_name='enrollmentcourse',
            index=models.Index(fields=['lecture_code'], name='idx_ec_lec_code'),
        ),
        migrations.AddIndex(
            model_name='enrollmentcourse',
            index=models.Index(fields=['course_ym', 'lecture_code'], name='idx_ec_ym_lec'),
        ),
        migrations.AddIndex(
            model_name='waitstudent',
            index=models.Index(fields=['del_chk', 'trans_gbn'], name='idx_wait_delchk_trans'),
        ),
        migrations.AddIndex(
            model_name='waitstudent',
            index=models.Index(fields=['sta_code', 'lecture_code'], name='idx_wait_sta_lec'),
        ),
    ]
