# Generated by Django 5.2.11 on 2026-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_enrollment_idx_enroll_delchk_stats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentBillSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_seq', models.IntegerField(db_index=True, default=0, verbose_name='원본번호')),
                ('no_seq', models.IntegerField(default=0, verbose_name='입단번호')),
                ('pknum', models.IntegerField(default=0, verbose_name='원본PK')),
                ('bill_code', models.CharField(max_length=4, verbose_name='청구코드')),
                ('bill_desc', models.CharField(blank=True, max_length=100, verbose_name='청구설명')),
                ('bill_amt', models.IntegerField(default=0, verbose_name='청구금액')),
                ('pay_stats', models.CharField(blank=True, max_length=2, verbose_name='결제상태')),
                ('insert_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '청구 변경원본',
                'verbose_name_plural': '청구 변경원본',
                'db_table': 'enrollment_enrollmentbillsrc',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSrc',
            fields=[
                ('src_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='원본번호')),
                ('no_seq', models.IntegerField(db_index=True, default=0, verbose_name='입단번호')),
                ('member_id', models.CharField(blank=True, max_length=30, verbose_name='학부모ID')),
                ('child_id', models.CharField(blank=True, max_length=30, verbose_name='자녀ID')),
                ('pay_stats', models.CharField(blank=True, max_length=2, verbose_name='결제상태')),
                ('pay_method', models.CharField(blank=True, max_length=10, verbose_name='결제방법')),
                ('pay_price', models.IntegerField(default=0, verbose_name='결제금액')),
                ('lecture_stats', models.CharField(blank=True, max_length=2, verbose_name='수강상태')),
                ('lec_cycle', models.IntegerField(default=0, verbose_name='주간횟수')),
                ('lec_period', models.IntegerField(default=0, verbose_name='수강기간(월)')),
                ('start_dt', models.CharField(blank=True, max_length=6, verbose_name='시작년월')),
                ('end_dt', models.CharField(blank=True, max_length=6, verbose_name='종료년월')),
                ('apply_gubun', models.CharField(blank=True, max_length=5, verbose_name='신청구분')),
                ('cancel_code', models.CharField(blank=True, max_length=10, verbose_name='취소사유코드')),
                ('cancel_desc', models.CharField(blank=True, max_length=200, verbose_name='취소사유')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_id', models.CharField(blank=True, max_length=30, verbose_name='등록자')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '입단 변경원본',
                'verbose_name_plural': '입단 변경원본',
                'db_table': 'enrollment_enrollmentsrc',
            },
        ),
    ]
