# Generated by Django 5.2.11 on 2026-06-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPaymentToss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_key', models.CharField(blank=True, max_length=200, verbose_name='결제키')),
                ('order_no', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('amount', models.IntegerField(default=0, verbose_name='결제금액')),
                ('method', models.CharField(blank=True, max_length=30, verbose_name='결제수단')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='결제상태')),
                ('use_pay_method', models.CharField(blank=True, max_length=20, verbose_name='결제수단코드')),
                ('http_code', models.IntegerField(default=0, verbose_name='HTTP상태')),
                ('res_cd', models.CharField(blank=True, max_length=50, verbose_name='응답코드')),
                ('res_msg', models.CharField(blank=True, max_length=300, verbose_name='응답메시지')),
                ('order_name', models.CharField(blank=True, max_length=200, verbose_name='상품명')),
                ('card_name', models.CharField(blank=True, max_length=50, verbose_name='카드명')),
                ('card_no', models.CharField(blank=True, max_length=30, verbose_name='카드번호')),
                ('app_no', models.CharField(blank=True, max_length=30, verbose_name='승인번호')),
                ('quota', models.CharField(blank=True, max_length=5, verbose_name='할부개월')),
                ('noinf', models.CharField(blank=True, max_length=5, verbose_name='무이자여부')),
                ('bank_name', models.CharField(blank=True, max_length=30, verbose_name='은행명')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='은행코드')),
                ('approved_at', models.CharField(blank=True, max_length=40, verbose_name='승인시각')),
                ('raw_response', models.TextField(blank=True, verbose_name='원본응답')),
                ('member_num', models.CharField(blank=True, max_length=30, verbose_name='회원아이디')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_payments', to='shop.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '쇼핑몰Toss결제',
                'verbose_name_plural': '쇼핑몰Toss결제',
                'db_table': 'shop_shoppaymenttoss',
                'ordering': ['-id'],
            },
        ),
    ]
