# Generated by Django 5.2.11 on 2026-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoppaymenttoss'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemoption',
            name='option_item_uid',
            field=models.IntegerField(default=0, verbose_name='옵션항목ID'),
        ),
    ]
