# Generated by Django 5.2.11 on 2026-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycoachdata',
            name='m1003_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdata',
            name='m1004_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdata',
            name='m1005_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdata',
            name='m1006_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdatamonth',
            name='m1004_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdatamonth',
            name='m1005_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdatanew',
            name='m1004_price',
        ),
        migrations.RemoveField(
            model_name='dailycoachdatanew',
            name='m1005_price',
        ),
        migrations.AddField(
            model_name='dailycoachdata',
            name='m10031_price',
            field=models.IntegerField(default=0, verbose_name='상품비1'),
        ),
        migrations.AddField(
            model_name='dailycoachdata',
            name='m10032_price',
            field=models.IntegerField(default=0, verbose_name='상품비2'),
        ),
        migrations.AddField(
            model_name='dailycoachdata',
            name='m1007_price',
            field=models.IntegerField(default=0, verbose_name='기타'),
        ),
        migrations.AddField(
            model_name='dailycoachdatamonth',
            name='m1003_b_price',
            field=models.IntegerField(default=0, verbose_name='상품비B'),
        ),
        migrations.AddField(
            model_name='dailycoachdatamonth',
            name='m1007_b_price',
            field=models.IntegerField(default=0, verbose_name='기타2B'),
        ),
        migrations.AddField(
            model_name='dailycoachdatamonth',
            name='m1009_b_price',
            field=models.IntegerField(default=0, verbose_name='기타3B'),
        ),
        migrations.AddField(
            model_name='dailycoachdatanew',
            name='m1003_b_price',
            field=models.IntegerField(default=0, verbose_name='상품비B'),
        ),
        migrations.AddField(
            model_name='dailycoachdatanew',
            name='m1007_b_price',
            field=models.IntegerField(default=0, verbose_name='기타2B'),
        ),
        migrations.AddField(
            model_name='dailycoachdatanew',
            name='m1009_b_price',
            field=models.IntegerField(default=0, verbose_name='기타3B'),
        ),
        migrations.AlterField(
            model_name='dailycoachdatamonth',
            name='m1006_price',
            field=models.IntegerField(default=0, verbose_name='기타1'),
        ),
        migrations.AlterField(
            model_name='dailycoachdatanew',
            name='m1006_price',
            field=models.IntegerField(default=0, verbose_name='기타1'),
        ),
    ]
