# Generated by Django 5.2.11 on 2026-02-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_dailycoachdata_m1003_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTotalData',
        ),
    ]
