# Generated by Django 5.2.11 on 2026-03-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_delete_dailytotaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCoachData',
        ),
        migrations.DeleteModel(
            name='DailyCoachDataMonth',
        ),
        migrations.DeleteModel(
            name='DailyCoachDataNew',
        ),
    ]
