# Generated by Django 5.2.11 on 2026-06-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_delete_dailycoachdata_delete_dailycoachdatamonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCoachDataNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_dt', models.CharField(max_length=8, verbose_name='처리일')),
                ('pay_seq', models.IntegerField(default=0, verbose_name='결제번호')),
                ('member_id', models.CharField(blank=True, max_length=30, verbose_name='회원ID')),
                ('child_id', models.CharField(blank=True, max_length=30, verbose_name='자녀ID')),
                ('order_id', models.CharField(blank=True, max_length=50, verbose_name='주문번호')),
                ('pay_dt', models.DateTimeField(blank=True, null=True, verbose_name='결제일시')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일시')),
                ('pay_method', models.CharField(blank=True, max_length=20, verbose_name='결제방법')),
                ('course_ym', models.CharField(blank=True, max_length=10, verbose_name='수강년월')),
                ('sta_code', models.IntegerField(default=0, verbose_name='구장코드')),
                ('lecture_code', models.IntegerField(default=0, verbose_name='강좌코드')),
                ('coach_code', models.IntegerField(default=0, verbose_name='코치코드')),
                ('coach_name', models.CharField(blank=True, max_length=30, verbose_name='코치명')),
                ('cl_cnt', models.IntegerField(default=0, verbose_name='수강건수')),
                ('m1001_price', models.IntegerField(default=0, verbose_name='수업료')),
                ('m1002_price', models.IntegerField(default=0, verbose_name='첫달차감')),
                ('m1003_price', models.IntegerField(default=0, verbose_name='수강료할인')),
                ('m1003_b_price', models.IntegerField(default=0, verbose_name='결제금액차감')),
                ('m1006_price', models.IntegerField(default=0, verbose_name='피추천할인')),
                ('m1007_b_price', models.IntegerField(default=0, verbose_name='다회할인')),
                ('m1009_b_price', models.IntegerField(default=0, verbose_name='차량이용료')),
                ('m2001_price', models.IntegerField(default=0, verbose_name='교육용품비')),
                ('m2002_price', models.IntegerField(default=0, verbose_name='교육용품할인')),
                ('regdate', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '일별 코치 정산',
                'verbose_name_plural': '일별 코치 정산',
                'db_table': 'reports_dailycoachdatanew',
                'indexes': [models.Index(fields=['proc_dt'], name='idx_dcdn_proc_dt'), models.Index(fields=['proc_dt', 'course_ym'], name='idx_dcdn_proc_ym'), models.Index(fields=['course_ym'], name='idx_dcdn_course_ym')],
            },
        ),
        migrations.CreateModel(
            name='DailyTotalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_dt', models.CharField(max_length=12, verbose_name='처리일')),
                ('rownum', models.BigIntegerField(default=0, verbose_name='순번')),
                ('no_seq', models.IntegerField(default=0, verbose_name='입단번호')),
                ('member_id', models.CharField(blank=True, max_length=30, verbose_name='회원ID')),
                ('member_name', models.CharField(blank=True, db_column='MEMBER_NAME', max_length=30, verbose_name='회원명')),
                ('child_id', models.CharField(blank=True, max_length=30, verbose_name='자녀ID')),
                ('mhtel', models.CharField(blank=True, max_length=30, verbose_name='휴대폰')),
                ('child_name', models.CharField(blank=True, db_column='CHILD_NAME', max_length=30, verbose_name='자녀명')),
                ('card_num', models.CharField(blank=True, db_column='CARD_NUM', max_length=8, verbose_name='카드번호')),
                ('apply_gubun', models.CharField(blank=True, max_length=30, verbose_name='신청구분')),
                ('sta_name', models.CharField(blank=True, max_length=50, verbose_name='구장명')),
                ('lecture_code', models.IntegerField(default=0, verbose_name='강좌코드')),
                ('lecture_title', models.CharField(blank=True, max_length=150, verbose_name='강좌명')),
                ('coach_name', models.CharField(blank=True, db_column='COACH_NAME', max_length=30, verbose_name='코치명')),
                ('lec_cycle', models.CharField(blank=True, max_length=1, verbose_name='주간횟수')),
                ('lec_period', models.CharField(blank=True, max_length=1, verbose_name='수강기간')),
                ('lecture_stats', models.CharField(blank=True, max_length=30, verbose_name='수강상태')),
                ('pay_price', models.IntegerField(default=0, verbose_name='결제금액')),
                ('lec_price', models.IntegerField(default=0, verbose_name='수업료')),
                ('join_price', models.IntegerField(default=0, verbose_name='교육용품비')),
                ('lec_course_ym_amt', models.IntegerField(default=0, verbose_name='월수강금액')),
                ('pay_stats', models.CharField(blank=True, max_length=12, verbose_name='결제상태')),
                ('pay_method', models.CharField(blank=True, max_length=14, verbose_name='결제방법')),
                ('pay_dt', models.CharField(blank=True, db_column='PAY_DT', max_length=10, verbose_name='결제일')),
                ('cancel_date', models.CharField(blank=True, max_length=10, verbose_name='취소일')),
                ('cancel_code', models.CharField(blank=True, max_length=4, verbose_name='취소코드')),
                ('cancel_desc', models.CharField(blank=True, max_length=100, verbose_name='취소사유')),
                ('start_dt', models.CharField(blank=True, max_length=6, verbose_name='시작월')),
                ('end_dt', models.CharField(blank=True, max_length=6, verbose_name='종료월')),
                ('course_ym', models.CharField(blank=True, max_length=7, verbose_name='수강년월')),
                ('course_ym_amt', models.IntegerField(default=0, verbose_name='수강금액')),
                ('insert_id', models.CharField(blank=True, max_length=16, verbose_name='등록자')),
                ('insert_dt', models.CharField(blank=True, db_column='INSERT_DT', max_length=10, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '일별 전체 스냅샷',
                'verbose_name_plural': '일별 전체 스냅샷',
                'db_table': 'reports_dailytotaldata',
                'indexes': [models.Index(fields=['proc_dt'], name='idx_dtd_proc_dt'), models.Index(fields=['proc_dt', 'course_ym'], name='idx_dtd_proc_ym')],
            },
        ),
    ]
