# Generated by Django 5.2.11 on 2026-02-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_seq', models.IntegerField(unique=True, verbose_name='알림번호')),
                ('atitle', models.CharField(max_length=100, verbose_name='제목')),
                ('acontent', models.TextField(blank=True, verbose_name='내용')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('reg_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('reg_id', models.CharField(blank=True, max_length=20, verbose_name='등록자ID')),
            ],
            options={
                'verbose_name': '사무실 알림',
                'verbose_name_plural': '사무실 알림',
                'db_table': 'notifications_officenotification',
                'ordering': ['-reg_dt'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_key', models.CharField(blank=True, max_length=20, verbose_name='메시지키')),
                ('date_client_req', models.DateTimeField(blank=True, null=True, verbose_name='발송요청일시')),
                ('subject', models.CharField(blank=True, max_length=40, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('callback', models.CharField(blank=True, max_length=25, verbose_name='발신번호')),
                ('service_type', models.CharField(blank=True, choices=[('0', 'SMS'), ('2', 'SMS'), ('3', 'LMS')], max_length=2, verbose_name='서비스유형')),
                ('msg_status', models.CharField(blank=True, max_length=1, verbose_name='발송상태')),
                ('recipient_num', models.CharField(blank=True, max_length=25, verbose_name='수신번호')),
                ('broadcast_yn', models.CharField(default='N', max_length=1, verbose_name='대량발송여부')),
                ('date_sent', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('date_rslt', models.DateTimeField(blank=True, null=True, verbose_name='결과수신일시')),
                ('rslt', models.CharField(blank=True, max_length=10, verbose_name='발송결과')),
            ],
            options={
                'verbose_name': 'SMS 로그',
                'verbose_name_plural': 'SMS 로그',
                'db_table': 'notifications_smslog',
                'ordering': ['-date_client_req'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_seq', models.IntegerField(unique=True, verbose_name='알림번호')),
                ('alim_gbn', models.CharField(choices=[('P', '학부모')], default='P', max_length=1, verbose_name='알림구분')),
                ('member_name', models.CharField(blank=True, max_length=20, verbose_name='회원명')),
                ('child_id', models.CharField(blank=True, max_length=16, verbose_name='자녀ID')),
                ('local_code', models.IntegerField(blank=True, null=True, verbose_name='권역코드')),
                ('sta_code', models.IntegerField(blank=True, null=True, verbose_name='구장코드')),
                ('lecture_code', models.IntegerField(blank=True, null=True, verbose_name='강좌코드')),
                ('alim_title', models.CharField(max_length=100, verbose_name='제목')),
                ('alim_content', models.TextField(blank=True, verbose_name='내용')),
                ('alim_file', models.CharField(blank=True, max_length=200, verbose_name='첨부파일')),
                ('del_chk', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('insert_id', models.CharField(blank=True, max_length=12, verbose_name='작성자ID')),
                ('insert_name', models.CharField(blank=True, max_length=20, verbose_name='작성자명')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('member', models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='회원')),
            ],
            options={
                'verbose_name': '알림장',
                'verbose_name_plural': '알림장',
                'db_table': 'notifications_notification',
                'ordering': ['-insert_dt'],
            },
        ),
    ]
